package abstraction.eq6Distributeur1;

public class Stocks extends Distributeur1Acteur{
	
	protected int TABLETTE_HAUTE_BIO_EQUITABLE;
	protected int TABLETTE_HAUTE_BIO;
	protected int TABLETTE_HAUTE_EQUITABLE;
	//protected int TABLETTE_HAUTE;
	protected int TABLETTE_MOYENNE_EQUITABLE;
	protected int TABLETTE_MOYENNE;
	protected int TABLETTE_BASSE;
	
	protected int CONFISERIE_HAUTE_BIO_EQUITABLE;
	//protected int CONFISERIE_HAUTE_BIO;
	protected int CONFISERIE_HAUTE_EQUITABLE;
	//protected int CONFISERIE_HAUTE;
	protected int CONFISERIE_MOYENNE_EQUITABLE;
	protected int CONFISERIE_MOYENNE;
	protected int CONFISERIE_BASSE;
	
	protected int POUDRE_HAUTE_BIO_EQUITABLE;
	//protected int POUDRE_HAUTE_BIO;
	//protected int POUDRE_HAUTE_EQUITABLE;
	//protected int POUDRE_HAUTE;
	protected int POUDRE_MOYENNE_EQUITABLE;
	protected int POUDRE_MOYENNE;
	protected int POUDRE_BASSE;

	
	public Stocks() {
		TABLETTE_HAUTE_BIO_EQUITABLE = 0;
		TABLETTE_HAUTE_BIO = 0;
		TABLETTE_HAUTE_EQUITABLE = 0;
		TABLETTE_MOYENNE_EQUITABLE = 0;
		TABLETTE_MOYENNE = 0;
		TABLETTE_BASSE = 0;
		CONFISERIE_HAUTE_BIO_EQUITABLE = 0;
		CONFISERIE_HAUTE_EQUITABLE = 0;
		CONFISERIE_MOYENNE_EQUITABLE = 0;
		CONFISERIE_MOYENNE = 0;
		CONFISERIE_BASSE = 0;
		POUDRE_HAUTE_BIO_EQUITABLE = 0;
		POUDRE_MOYENNE_EQUITABLE = 0;
		POUDRE_MOYENNE = 0;
		POUDRE_BASSE = 0;
	}
	
	
	

	

}
