package abstraction.eq6Distributeur1;

public class Stocks {
	
	private int TABLETTE_HAUTE_BIO_EQUITABLE;
	private int TABLETTE_HAUTE_BIO;
	private int TABLETTE_HAUTE_EQUITABLE;
	//private int TABLETTE_HAUTE;
	private int TABLETTE_MOYENNE_EQUITABLE;
	private int TABLETTE_MOYENNE;
	private int TABLETTE_BASSE;
	
	private int CONFISERIE_HAUTE_BIO_EQUITABLE;
	//private int CONFISERIE_HAUTE_BIO;
	private int CONFISERIE_HAUTE_EQUITABLE;
	//private int CONFISERIE_HAUTE;
	private int CONFISERIE_MOYENNE_EQUITABLE;
	private int CONFISERIE_MOYENNE;
	private int CONFISERIE_BASSE;
	
	private int POUDRE_HAUTE_BIO_EQUITABLE;
	//private int POUDRE_HAUTE_BIO;
	//private int POUDRE_HAUTE_EQUITABLE;
	//private int POUDRE_HAUTE;
	private int POUDRE_MOYENNE_EQUITABLE;
	private int POUDRE_MOYENNE;
	private int POUDRE_BASSE;

	
	public Stocks() {
		TABLETTE_HAUTE_BIO_EQUITABLE = 0;
		TABLETTE_HAUTE_BIO = 0;
		TABLETTE_HAUTE_EQUITABLE = 0;
		TABLETTE_MOYENNE_EQUITABLE = 0;
		TABLETTE_MOYENNE = 0;
		TABLETTE_BASSE = 0;
		CONFISERIE_HAUTE_BIO_EQUITABLE = 0;
		CONFISERIE_HAUTE_EQUITABLE = 0;
		CONFISERIE_MOYENNE_EQUITABLE = 0;
		CONFISERIE_MOYENNE = 0;
		CONFISERIE_BASSE = 0;
		POUDRE_HAUTE_BIO_EQUITABLE = 0;
		POUDRE_MOYENNE_EQUITABLE = 0;
		POUDRE_MOYENNE = 0;
		POUDRE_BASSE = 0;
	}
	
	
	

	

}
